-- MySQL Script generated by MySQL Workbench
-- Tue Feb  6 00:15:28 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema rewards
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `rewards` ;

-- -----------------------------------------------------
-- Schema rewards
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rewards` DEFAULT CHARACTER SET utf8 ;
USE `rewards` ;

-- -----------------------------------------------------
-- Table `rewards`.`award_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rewards`.`award_type` ;

CREATE TABLE IF NOT EXISTS `rewards`.`award_type` (
  `award_type_id` INT(11) NOT NULL AUTO_INCREMENT,
  `type_description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`award_type_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rewards`.`customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rewards`.`customers` ;

CREATE TABLE IF NOT EXISTS `rewards`.`customers` (
  `customer_id` INT(11) NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NULL DEFAULT NULL,
  `last_name` VARCHAR(50) NULL DEFAULT NULL,
  `birthdate` DATETIME NULL DEFAULT NULL,
  `enroll_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `email_address` VARCHAR(100) NOT NULL,
  `phone_number` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `idx_email_address` ON `rewards`.`customers` (`email_address` ASC);

CREATE INDEX `idx_phone_number` ON `rewards`.`customers` (`phone_number` ASC);


-- -----------------------------------------------------
-- Table `rewards`.`transactions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rewards`.`transactions` ;

CREATE TABLE IF NOT EXISTS `rewards`.`transactions` (
  `txn_id` INT(11) NOT NULL AUTO_INCREMENT,
  `customer_id` INT(11) NOT NULL,
  `purchase_amt` DECIMAL(9,2) NOT NULL DEFAULT '0.00',
  `tax_amt` DECIMAL(9,2) NOT NULL DEFAULT '0.00',
  `txn_date` DATETIME NOT NULL,
  PRIMARY KEY (`txn_id`),
  CONSTRAINT `fk_customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `rewards`.`customers` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `idx_txn_date` ON `rewards`.`transactions` (`customer_id` ASC, `txn_date` ASC);


-- -----------------------------------------------------
-- Table `rewards`.`awards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rewards`.`awards` ;

CREATE TABLE IF NOT EXISTS `rewards`.`awards` (
  `award_id` INT(11) NOT NULL AUTO_INCREMENT,
  `customer_id` INT(11) NOT NULL,
  `award_type_id` INT(11) NOT NULL,
  `txn_id` INT(11) NULL DEFAULT NULL,
  `point_earn` TINYINT(4) NOT NULL DEFAULT '1',
  `points` INT(11) NOT NULL,
  `award_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`award_id`),
  CONSTRAINT `fk_award_customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `rewards`.`customers` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_award_txn_id`
    FOREIGN KEY (`txn_id`)
    REFERENCES `rewards`.`transactions` (`txn_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_award_type_id`
    FOREIGN KEY (`award_type_id`)
    REFERENCES `rewards`.`award_type` (`award_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_customer_id_idx` ON `rewards`.`awards` (`customer_id` ASC);

CREATE INDEX `idx_award_date` ON `rewards`.`awards` (`award_date` ASC, `customer_id` ASC);

CREATE INDEX `fk_award_type_id_idx` ON `rewards`.`awards` (`award_type_id` ASC);

CREATE INDEX `fk_award_txn_id_idx` ON `rewards`.`awards` (`txn_id` ASC);


-- -----------------------------------------------------
-- Table `rewards`.`rewards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rewards`.`rewards` ;

CREATE TABLE IF NOT EXISTS `rewards`.`rewards` (
  `reward_id` INT(11) NOT NULL AUTO_INCREMENT,
  `customer_id` INT(11) NOT NULL,
  `points` INT(11) NOT NULL,
  `reward_date` DATETIME NOT NULL,
  PRIMARY KEY (`reward_id`),
  CONSTRAINT `fk_rewards_customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `rewards`.`customers` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_rewards_customer_id_idx` ON `rewards`.`rewards` (`customer_id` ASC);

CREATE INDEX `idx_reward_date` ON `rewards`.`rewards` (`reward_date` ASC, `customer_id` ASC);


-- -----------------------------------------------------
-- Table `rewards`.`summary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rewards`.`summary` ;

CREATE TABLE IF NOT EXISTS `rewards`.`summary` (
  `customer_id` INT(11) NOT NULL,
  `points` INT(11) NOT NULL DEFAULT '0',
  `total_rewards` INT(11) NOT NULL DEFAULT '0',
  `total_awards` INT(11) NOT NULL DEFAULT '0',
  `last_updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`customer_id`),
  CONSTRAINT `fk_summary_customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `rewards`.`customers` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
